language: node_js
node_js:
  - "8"
dist: trusty
env:
    - PORT=3000
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
  


